### ISSUE TITLE
Add more options 

### ISSUE THREAD

**Issue by swati2603** [krishguptadev/Bin2Dec#3]
Like binary to octal or binary to hexadecimal.

**Comment by krishguptadev** [comment]
Thank you for reporting this issue. A fix will be made soon!

**Comment by swati2603** [comment]
Can I work on this issue? 
If yes, then assign me.

**Comment by krishguptadev** [comment]
cool! You can work on this, I'll assign you

**Comment by swati2603** [comment]
Thank you
